// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm4XuSSKEzsQnzrTlcls6U8MTN0tihBSc',
    appId: '1:865255980484:web:18236499f924ad6c8d7891',
    messagingSenderId: '865255980484',
    projectId: 'wfirebase-ac841',
    authDomain: 'wfirebase-ac841.firebaseapp.com',
    databaseURL: 'https://wfirebase-ac841-default-rtdb.firebaseio.com',
    storageBucket: 'wfirebase-ac841.firebasestorage.app',
    measurementId: 'G-VY9H2ZRZPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkoJ_5rSf5LwM60Az3RMfPj4Cf09Gj8EQ',
    appId: '1:865255980484:android:a7f3260aa43896bb8d7891',
    messagingSenderId: '865255980484',
    projectId: 'wfirebase-ac841',
    databaseURL: 'https://wfirebase-ac841-default-rtdb.firebaseio.com',
    storageBucket: 'wfirebase-ac841.firebasestorage.app',
  );
}
