// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwgzVH-CCAtsL_CdRMPJY5x8OaskLOVq4',
    appId: '1:497895192428:web:2710399436058614fd2549',
    messagingSenderId: '497895192428',
    projectId: 'introfirebase1-9fc7b',
    authDomain: 'introfirebase1-9fc7b.firebaseapp.com',
    databaseURL: 'https://introfirebase1-9fc7b-default-rtdb.firebaseio.com',
    storageBucket: 'introfirebase1-9fc7b.firebasestorage.app',
    measurementId: 'G-PZS0ED0BM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ8Inlp2TzU_ARWNSNErjdlrbRmRr_bUE',
    appId: '1:497895192428:android:2d833bc0564c99b6fd2549',
    messagingSenderId: '497895192428',
    projectId: 'introfirebase1-9fc7b',
    databaseURL: 'https://introfirebase1-9fc7b-default-rtdb.firebaseio.com',
    storageBucket: 'introfirebase1-9fc7b.firebasestorage.app',
  );
}
